//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP22NET.DATA.ClassesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certification
    {
        public int Id { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
