//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP22NET.DATA.ClassesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repartition
    {
        public int Id { get; set; }
        public int TeacherId { get; set; }
        public string CoursesId { get; set; }
        public string Campus { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
