//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP22NET.DATA.ClassesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Repartition = new HashSet<Repartition>();
            this.Certification = new HashSet<Certification>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Firstname { get; set; }
        public Nullable<int> PromoDuring { get; set; }
        public Nullable<int> PromoCurrent { get; set; }
        public string Email { get; set; }
        public string Campus { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Repartition> Repartition { get; set; }
        public virtual ICollection<Certification> Certification { get; set; }
    }
}
